### ISSUE TITLE
Training time?

### ISSUE THREAD

**Issue by Becomebright** [MCG-NJU/MixFormer#1]
Thanks for your solid work. How long does it take to train the Base and Large model on V100 or 2080Ti?

**Comment by yutaocui** [comment]
For the Base model:
    --V100: ~40h
    --2080Ti: ~3d20h
For the Large model:
    --V100: ~3d+
We didn't train MixFormer-L on 2080Ti since it requires large gpu memory.

**Comment by Becomebright** [comment]
Thanks a lot.

**Comment by yutaocui** [comment]
> May I ask the training time metioned above is under lmdb data format or not?

Not the lmdb data format.

**Comment by samueleruffino99** [comment]
I am training the base_large model on a GPU with 12 GB of RAM memory. As soon as I increase the batch size to more than 1 I am getting "CUDA out of memory issue". I am wondering how much memory did you have on your V100 GPU, 32 GB? Anyway it is strange since I was expecting to settle a batch size of 4 or so. Thank you!!
