### ISSUE TITLE
About Score Prediction Module (SPM) and MixFormer-1k

### ISSUE THREAD

**Issue by hhhAlan** [MCG-NJU/MixFormer#3]
Hi, Thanks for your work. I have some questions about your paper:
1. Have you ever tried to use the score prediction module of STARK (MLP) instead of the SPM proposed in your paper? I am curious about the performance difference between  SPM and using MLP directly.
2. The MixFormer-1k model seems to be trained with all dataset, not just the GOT10k, which is different from your paper (it is unreasonable that MixFormer-1k performs better than MixFormer-GOT if MixFormer-1k is also trained with GOT10k only). Is it fair to use it for comparison on GOT10k  test?

**Comment by yutaocui** [comment]
Thanks for your attention.
For the 1st question, we can not directly use STARK's since MixFormer doesn't possess an explicit query and decoder for the tracking object. The main differences are as follows.
1) we explicitly input the tracked object RoI feature (cropped based on MixFormer's tracking results) of the current frame to the SPM, while STARK implicitly extract the target information through an encoder-decoder structure.
2) There is no decoder like STARK's in MixFormer, so that we introduce an extra score token and two attention modules. 
3) SPM is composed of two progressive attention blocks to take comparison between tracked object and the target, while STARK employs a a three-layer perceptron head.

**Comment by yutaocui** [comment]
For the 2nd question, we have updated the got-10k results of Imagenet1k-pretraining. (we will update the paper in the next version.)
<img width="425" alt="截屏2022-03-25 下午3 43 12" src="https://user-images.githubusercontent.com/40455558/160077825-f662474e-6ce4-46ae-8523-aba9a1144b10.png">

**Comment by wanglimin** [comment]
It should be note that in our current version, the performance of 71.2 AO is obtained only with got-10k training videos (**not all dataset**). With all dataset, we obtain 73.2 AO. We will make this more clear in the next version

**Comment by hhhAlan** [comment]
Ok, thanks for your relay.
